<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace next_test\a\Models\Operations;

use \next_test\a\Utils\SpeakeasyMetadata;
class ListPetsRequest
{
    /**
     * How many items to return at one time (max 100)
     * 
     * @var ?int $limit
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;
    
	public function __construct()
	{
		$this->limit = null;
	}
}
