<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace next_test\a\Models\Operations;

use \next_test\a\Utils\SpeakeasyMetadata;
class ShowPetByIdRequest
{
    /**
     * The id of the pet to retrieve
     * 
     * @var string $petId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=petId')]
    public string $petId;
    
	public function __construct()
	{
		$this->petId = "";
	}
}
