<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace next_test\a;

/**
 * A
 * 
 * @package next_test\a
 * @access public
 */
class A
{
	public const SERVERS = [
		'http://petstore.swagger.io/v1',
	];
  	
	public Pets $pets;
	

	/**
	 * Returns a new instance of the SDK builder used to configure and create the SDK instance.
	 * 
	 * @return ABuilder
	 */
	public static function builder(): ABuilder
	{
		return new ABuilder();
	}

	/**
	 * @param SDKConfiguration $sdkConfiguration
	 */
	public function __construct(
		private SDKConfiguration $sdkConfiguration,
	) {
		
		$this->pets = new Pets($this->sdkConfiguration);
	}
}